name: untitled3
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk:  '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  provider: ^6.1.1
  intl: ^0.19.0
  fluttertoast: ^8.2.5
  flutter_secure_storage: ^9.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  flutter_map_location_marker: ^8.0.8
  permission_handler: ^11.3.0
  confetti: ^0.7.0
  location: ^5.0.0
  shared_preferences: ^2.0.8
  url_launcher: ^6.2.5
  webview_flutter: ^2.0.13
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3
  web_socket_channel: ^3.0.0
  firebase_messaging: ^14.9.2
  firebase_core: ^2.31.0
  flutter_local_notifications: ^17.1.2
  flutter_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  lottie: ^3.1.2
  animated_splash_screen: ^1.3.0
  flutter_launcher_icons: ^0.13.1
  firebase_analytics: ^10.10.7
  flutter_rating_bar: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Medium.ttf
    - family: Poppins
      fonts:
        - asset: fonts/Poppins.ttf
